use crate::bindings::{
    SDL_KeyCode, SDL_KeyCode_SDLK_0, SDL_KeyCode_SDLK_1, SDL_KeyCode_SDLK_2, SDL_KeyCode_SDLK_3,
    SDL_KeyCode_SDLK_4, SDL_KeyCode_SDLK_5, SDL_KeyCode_SDLK_6, SDL_KeyCode_SDLK_7,
    SDL_KeyCode_SDLK_8, SDL_KeyCode_SDLK_9, SDL_KeyCode_SDLK_AGAIN, SDL_KeyCode_SDLK_ALTERASE,
    SDL_KeyCode_SDLK_AMPERSAND, SDL_KeyCode_SDLK_APPLICATION, SDL_KeyCode_SDLK_ASTERISK,
    SDL_KeyCode_SDLK_AT, SDL_KeyCode_SDLK_BACKQUOTE, SDL_KeyCode_SDLK_BACKSLASH,
    SDL_KeyCode_SDLK_BACKSPACE, SDL_KeyCode_SDLK_CANCEL, SDL_KeyCode_SDLK_CAPSLOCK,
    SDL_KeyCode_SDLK_CARET, SDL_KeyCode_SDLK_CLEAR, SDL_KeyCode_SDLK_CLEARAGAIN,
    SDL_KeyCode_SDLK_COLON, SDL_KeyCode_SDLK_COMMA, SDL_KeyCode_SDLK_COPY, SDL_KeyCode_SDLK_CRSEL,
    SDL_KeyCode_SDLK_CURRENCYSUBUNIT, SDL_KeyCode_SDLK_CURRENCYUNIT, SDL_KeyCode_SDLK_CUT,
    SDL_KeyCode_SDLK_DECIMALSEPARATOR, SDL_KeyCode_SDLK_DELETE, SDL_KeyCode_SDLK_DOLLAR,
    SDL_KeyCode_SDLK_DOWN, SDL_KeyCode_SDLK_END, SDL_KeyCode_SDLK_EQUALS, SDL_KeyCode_SDLK_ESCAPE,
    SDL_KeyCode_SDLK_EXCLAIM, SDL_KeyCode_SDLK_EXECUTE, SDL_KeyCode_SDLK_EXSEL,
    SDL_KeyCode_SDLK_F1, SDL_KeyCode_SDLK_F10, SDL_KeyCode_SDLK_F11, SDL_KeyCode_SDLK_F12,
    SDL_KeyCode_SDLK_F13, SDL_KeyCode_SDLK_F14, SDL_KeyCode_SDLK_F15, SDL_KeyCode_SDLK_F16,
    SDL_KeyCode_SDLK_F17, SDL_KeyCode_SDLK_F18, SDL_KeyCode_SDLK_F19, SDL_KeyCode_SDLK_F2,
    SDL_KeyCode_SDLK_F20, SDL_KeyCode_SDLK_F21, SDL_KeyCode_SDLK_F22, SDL_KeyCode_SDLK_F23,
    SDL_KeyCode_SDLK_F24, SDL_KeyCode_SDLK_F3, SDL_KeyCode_SDLK_F4, SDL_KeyCode_SDLK_F5,
    SDL_KeyCode_SDLK_F6, SDL_KeyCode_SDLK_F7, SDL_KeyCode_SDLK_F8, SDL_KeyCode_SDLK_F9,
    SDL_KeyCode_SDLK_FIND, SDL_KeyCode_SDLK_GREATER, SDL_KeyCode_SDLK_HASH, SDL_KeyCode_SDLK_HELP,
    SDL_KeyCode_SDLK_HOME, SDL_KeyCode_SDLK_INSERT, SDL_KeyCode_SDLK_KP_0, SDL_KeyCode_SDLK_KP_00,
    SDL_KeyCode_SDLK_KP_000, SDL_KeyCode_SDLK_KP_1, SDL_KeyCode_SDLK_KP_2, SDL_KeyCode_SDLK_KP_3,
    SDL_KeyCode_SDLK_KP_4, SDL_KeyCode_SDLK_KP_5, SDL_KeyCode_SDLK_KP_6, SDL_KeyCode_SDLK_KP_7,
    SDL_KeyCode_SDLK_KP_8, SDL_KeyCode_SDLK_KP_9, SDL_KeyCode_SDLK_KP_BACKSPACE,
    SDL_KeyCode_SDLK_KP_COMMA, SDL_KeyCode_SDLK_KP_DIVIDE, SDL_KeyCode_SDLK_KP_ENTER,
    SDL_KeyCode_SDLK_KP_EQUALS, SDL_KeyCode_SDLK_KP_EQUALSAS400, SDL_KeyCode_SDLK_KP_LEFTBRACE,
    SDL_KeyCode_SDLK_KP_LEFTPAREN, SDL_KeyCode_SDLK_KP_MINUS, SDL_KeyCode_SDLK_KP_MULTIPLY,
    SDL_KeyCode_SDLK_KP_PERIOD, SDL_KeyCode_SDLK_KP_PLUS, SDL_KeyCode_SDLK_KP_RIGHTBRACE,
    SDL_KeyCode_SDLK_KP_RIGHTPAREN, SDL_KeyCode_SDLK_KP_TAB, SDL_KeyCode_SDLK_LEFT,
    SDL_KeyCode_SDLK_LEFTBRACKET, SDL_KeyCode_SDLK_LEFTPAREN, SDL_KeyCode_SDLK_LESS,
    SDL_KeyCode_SDLK_MENU, SDL_KeyCode_SDLK_MINUS, SDL_KeyCode_SDLK_MUTE,
    SDL_KeyCode_SDLK_NUMLOCKCLEAR, SDL_KeyCode_SDLK_OPER, SDL_KeyCode_SDLK_OUT,
    SDL_KeyCode_SDLK_PAGEDOWN, SDL_KeyCode_SDLK_PAGEUP, SDL_KeyCode_SDLK_PASTE,
    SDL_KeyCode_SDLK_PAUSE, SDL_KeyCode_SDLK_PERCENT, SDL_KeyCode_SDLK_PERIOD,
    SDL_KeyCode_SDLK_PLUS, SDL_KeyCode_SDLK_POWER, SDL_KeyCode_SDLK_PRINTSCREEN,
    SDL_KeyCode_SDLK_PRIOR, SDL_KeyCode_SDLK_QUESTION, SDL_KeyCode_SDLK_QUOTE,
    SDL_KeyCode_SDLK_QUOTEDBL, SDL_KeyCode_SDLK_RETURN, SDL_KeyCode_SDLK_RETURN2,
    SDL_KeyCode_SDLK_RIGHT, SDL_KeyCode_SDLK_RIGHTBRACKET, SDL_KeyCode_SDLK_RIGHTPAREN,
    SDL_KeyCode_SDLK_SCROLLLOCK, SDL_KeyCode_SDLK_SELECT, SDL_KeyCode_SDLK_SEMICOLON,
    SDL_KeyCode_SDLK_SEPARATOR, SDL_KeyCode_SDLK_SLASH, SDL_KeyCode_SDLK_SPACE,
    SDL_KeyCode_SDLK_STOP, SDL_KeyCode_SDLK_SYSREQ, SDL_KeyCode_SDLK_TAB,
    SDL_KeyCode_SDLK_THOUSANDSSEPARATOR, SDL_KeyCode_SDLK_UNDERSCORE, SDL_KeyCode_SDLK_UNDO,
    SDL_KeyCode_SDLK_UNKNOWN, SDL_KeyCode_SDLK_UP, SDL_KeyCode_SDLK_VOLUMEDOWN,
    SDL_KeyCode_SDLK_VOLUMEUP, SDL_KeyCode_SDLK_a, SDL_KeyCode_SDLK_b, SDL_KeyCode_SDLK_c,
    SDL_KeyCode_SDLK_d, SDL_KeyCode_SDLK_e, SDL_KeyCode_SDLK_f, SDL_KeyCode_SDLK_g,
    SDL_KeyCode_SDLK_h, SDL_KeyCode_SDLK_i, SDL_KeyCode_SDLK_j, SDL_KeyCode_SDLK_k,
    SDL_KeyCode_SDLK_l, SDL_KeyCode_SDLK_m, SDL_KeyCode_SDLK_n, SDL_KeyCode_SDLK_o,
    SDL_KeyCode_SDLK_p, SDL_KeyCode_SDLK_q, SDL_KeyCode_SDLK_r, SDL_KeyCode_SDLK_s,
    SDL_KeyCode_SDLK_t, SDL_KeyCode_SDLK_u, SDL_KeyCode_SDLK_v, SDL_KeyCode_SDLK_w,
    SDL_KeyCode_SDLK_x, SDL_KeyCode_SDLK_y, SDL_KeyCode_SDLK_z,
};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum KeyCode {
    Unknown,
    Return,
    Escape,
    Backspace,
    Tab,
    Space,
    Exclaim,
    Quotedbl,
    Hash,
    Percent,
    Dollar,
    Ampersand,
    Quote,
    LeftParen,
    RightParen,
    Asterisk,
    Plus,
    Comma,
    Minus,
    Period,
    Slash,
    Num0,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    Colon,
    Semicolon,
    Less,
    Equals,
    Greater,
    Question,
    At,
    LeftBracket,
    Backslash,
    RightBracket,
    Caret,
    Underscore,
    Backquote,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    CapsLock,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    PrintScreen,
    ScrollLock,
    Pause,
    Insert,
    Home,
    PageUp,
    Delete,
    End,
    PageDown,
    Right,
    Left,
    Down,
    Up,
    NumLockClear,
    KpDivide,
    KpMultiply,
    KpMinus,
    KpPlus,
    KpEnter,
    Kp1,
    Kp2,
    Kp3,
    Kp4,
    Kp5,
    Kp6,
    Kp7,
    Kp8,
    Kp9,
    Kp0,
    KpPeriod,
    Application,
    Power,
    KpEquals,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    Execute,
    Help,
    Menu,
    Select,
    Stop,
    Again,
    Undo,
    Cut,
    Copy,
    Paste,
    Find,
    Mute,
    VolumeUp,
    VolumeDown,
    KpComma,
    KpEqualsAS400,
    AltErase,
    Sysreq,
    Cancel,
    Clear,
    Prior,
    Return2,
    Separator,
    Out,
    Oper,
    ClearAgain,
    CrSel,
    ExSel,
    Kp00,
    Kp000,
    ThousandsSeparator,
    DecimalSeparator,
    CurrencyUnit,
    CurrencySubUnit,
    KpLeftParen,
    KpRightParen,
    KpLeftBrace,
    KpRightBrace,
    KpTab,
    KpBackspace,
}

impl From<u32> for KeyCode {
    fn from(value: u32) -> Self {
        let value = value as SDL_KeyCode;
        #[allow(non_upper_case_globals)]
        match value {
            SDL_KeyCode_SDLK_UNKNOWN => Self::Unknown,
            SDL_KeyCode_SDLK_RETURN => Self::Return,
            SDL_KeyCode_SDLK_ESCAPE => Self::Escape,
            SDL_KeyCode_SDLK_BACKSPACE => Self::Backspace,
            SDL_KeyCode_SDLK_TAB => Self::Tab,
            SDL_KeyCode_SDLK_SPACE => Self::Space,
            SDL_KeyCode_SDLK_EXCLAIM => Self::Exclaim,
            SDL_KeyCode_SDLK_QUOTEDBL => Self::Quotedbl,
            SDL_KeyCode_SDLK_HASH => Self::Hash,
            SDL_KeyCode_SDLK_PERCENT => Self::Percent,
            SDL_KeyCode_SDLK_DOLLAR => Self::Dollar,
            SDL_KeyCode_SDLK_AMPERSAND => Self::Ampersand,
            SDL_KeyCode_SDLK_QUOTE => Self::Quote,
            SDL_KeyCode_SDLK_LEFTPAREN => Self::LeftParen,
            SDL_KeyCode_SDLK_RIGHTPAREN => Self::RightParen,
            SDL_KeyCode_SDLK_ASTERISK => Self::Asterisk,
            SDL_KeyCode_SDLK_PLUS => Self::Plus,
            SDL_KeyCode_SDLK_COMMA => Self::Comma,
            SDL_KeyCode_SDLK_MINUS => Self::Minus,
            SDL_KeyCode_SDLK_PERIOD => Self::Period,
            SDL_KeyCode_SDLK_SLASH => Self::Slash,
            SDL_KeyCode_SDLK_0 => Self::Num0,
            SDL_KeyCode_SDLK_1 => Self::Num1,
            SDL_KeyCode_SDLK_2 => Self::Num2,
            SDL_KeyCode_SDLK_3 => Self::Num3,
            SDL_KeyCode_SDLK_4 => Self::Num4,
            SDL_KeyCode_SDLK_5 => Self::Num5,
            SDL_KeyCode_SDLK_6 => Self::Num6,
            SDL_KeyCode_SDLK_7 => Self::Num7,
            SDL_KeyCode_SDLK_8 => Self::Num8,
            SDL_KeyCode_SDLK_9 => Self::Num9,
            SDL_KeyCode_SDLK_COLON => Self::Colon,
            SDL_KeyCode_SDLK_SEMICOLON => Self::Semicolon,
            SDL_KeyCode_SDLK_LESS => Self::Less,
            SDL_KeyCode_SDLK_EQUALS => Self::Equals,
            SDL_KeyCode_SDLK_GREATER => Self::Greater,
            SDL_KeyCode_SDLK_QUESTION => Self::Question,
            SDL_KeyCode_SDLK_AT => Self::At,
            SDL_KeyCode_SDLK_LEFTBRACKET => Self::LeftBracket,
            SDL_KeyCode_SDLK_BACKSLASH => Self::Backslash,
            SDL_KeyCode_SDLK_RIGHTBRACKET => Self::RightBracket,
            SDL_KeyCode_SDLK_CARET => Self::Caret,
            SDL_KeyCode_SDLK_UNDERSCORE => Self::Underscore,
            SDL_KeyCode_SDLK_BACKQUOTE => Self::Backquote,
            SDL_KeyCode_SDLK_a => Self::A,
            SDL_KeyCode_SDLK_b => Self::B,
            SDL_KeyCode_SDLK_c => Self::C,
            SDL_KeyCode_SDLK_d => Self::D,
            SDL_KeyCode_SDLK_e => Self::E,
            SDL_KeyCode_SDLK_f => Self::F,
            SDL_KeyCode_SDLK_g => Self::G,
            SDL_KeyCode_SDLK_h => Self::H,
            SDL_KeyCode_SDLK_i => Self::I,
            SDL_KeyCode_SDLK_j => Self::J,
            SDL_KeyCode_SDLK_k => Self::K,
            SDL_KeyCode_SDLK_l => Self::L,
            SDL_KeyCode_SDLK_m => Self::M,
            SDL_KeyCode_SDLK_n => Self::N,
            SDL_KeyCode_SDLK_o => Self::O,
            SDL_KeyCode_SDLK_p => Self::P,
            SDL_KeyCode_SDLK_q => Self::Q,
            SDL_KeyCode_SDLK_r => Self::R,
            SDL_KeyCode_SDLK_s => Self::S,
            SDL_KeyCode_SDLK_t => Self::T,
            SDL_KeyCode_SDLK_u => Self::U,
            SDL_KeyCode_SDLK_v => Self::V,
            SDL_KeyCode_SDLK_w => Self::W,
            SDL_KeyCode_SDLK_x => Self::X,
            SDL_KeyCode_SDLK_y => Self::Y,
            SDL_KeyCode_SDLK_z => Self::Z,
            SDL_KeyCode_SDLK_CAPSLOCK => Self::CapsLock,
            SDL_KeyCode_SDLK_F1 => Self::F1,
            SDL_KeyCode_SDLK_F2 => Self::F2,
            SDL_KeyCode_SDLK_F3 => Self::F3,
            SDL_KeyCode_SDLK_F4 => Self::F4,
            SDL_KeyCode_SDLK_F5 => Self::F5,
            SDL_KeyCode_SDLK_F6 => Self::F6,
            SDL_KeyCode_SDLK_F7 => Self::F7,
            SDL_KeyCode_SDLK_F8 => Self::F8,
            SDL_KeyCode_SDLK_F9 => Self::F9,
            SDL_KeyCode_SDLK_F10 => Self::F10,
            SDL_KeyCode_SDLK_F11 => Self::F11,
            SDL_KeyCode_SDLK_F12 => Self::F12,
            SDL_KeyCode_SDLK_PRINTSCREEN => Self::PrintScreen,
            SDL_KeyCode_SDLK_SCROLLLOCK => Self::ScrollLock,
            SDL_KeyCode_SDLK_PAUSE => Self::Pause,
            SDL_KeyCode_SDLK_INSERT => Self::Insert,
            SDL_KeyCode_SDLK_HOME => Self::Home,
            SDL_KeyCode_SDLK_PAGEUP => Self::PageUp,
            SDL_KeyCode_SDLK_DELETE => Self::Delete,
            SDL_KeyCode_SDLK_END => Self::End,
            SDL_KeyCode_SDLK_PAGEDOWN => Self::PageDown,
            SDL_KeyCode_SDLK_RIGHT => Self::Right,
            SDL_KeyCode_SDLK_LEFT => Self::Left,
            SDL_KeyCode_SDLK_DOWN => Self::Down,
            SDL_KeyCode_SDLK_UP => Self::Up,
            SDL_KeyCode_SDLK_NUMLOCKCLEAR => Self::NumLockClear,
            SDL_KeyCode_SDLK_KP_DIVIDE => Self::KpDivide,
            SDL_KeyCode_SDLK_KP_MULTIPLY => Self::KpMultiply,
            SDL_KeyCode_SDLK_KP_MINUS => Self::KpMinus,
            SDL_KeyCode_SDLK_KP_PLUS => Self::KpPlus,
            SDL_KeyCode_SDLK_KP_ENTER => Self::KpEnter,
            SDL_KeyCode_SDLK_KP_1 => Self::Kp1,
            SDL_KeyCode_SDLK_KP_2 => Self::Kp2,
            SDL_KeyCode_SDLK_KP_3 => Self::Kp3,
            SDL_KeyCode_SDLK_KP_4 => Self::Kp4,
            SDL_KeyCode_SDLK_KP_5 => Self::Kp5,
            SDL_KeyCode_SDLK_KP_6 => Self::Kp6,
            SDL_KeyCode_SDLK_KP_7 => Self::Kp7,
            SDL_KeyCode_SDLK_KP_8 => Self::Kp8,
            SDL_KeyCode_SDLK_KP_9 => Self::Kp9,
            SDL_KeyCode_SDLK_KP_0 => Self::Kp0,
            SDL_KeyCode_SDLK_KP_PERIOD => Self::KpPeriod,
            SDL_KeyCode_SDLK_APPLICATION => Self::Application,
            SDL_KeyCode_SDLK_POWER => Self::Power,
            SDL_KeyCode_SDLK_KP_EQUALS => Self::KpEquals,
            SDL_KeyCode_SDLK_F13 => Self::F13,
            SDL_KeyCode_SDLK_F14 => Self::F14,
            SDL_KeyCode_SDLK_F15 => Self::F15,
            SDL_KeyCode_SDLK_F16 => Self::F16,
            SDL_KeyCode_SDLK_F17 => Self::F17,
            SDL_KeyCode_SDLK_F18 => Self::F18,
            SDL_KeyCode_SDLK_F19 => Self::F19,
            SDL_KeyCode_SDLK_F20 => Self::F20,
            SDL_KeyCode_SDLK_F21 => Self::F21,
            SDL_KeyCode_SDLK_F22 => Self::F22,
            SDL_KeyCode_SDLK_F23 => Self::F23,
            SDL_KeyCode_SDLK_F24 => Self::F24,
            SDL_KeyCode_SDLK_EXECUTE => Self::Execute,
            SDL_KeyCode_SDLK_HELP => Self::Help,
            SDL_KeyCode_SDLK_MENU => Self::Menu,
            SDL_KeyCode_SDLK_SELECT => Self::Select,
            SDL_KeyCode_SDLK_STOP => Self::Stop,
            SDL_KeyCode_SDLK_AGAIN => Self::Again,
            SDL_KeyCode_SDLK_UNDO => Self::Undo,
            SDL_KeyCode_SDLK_CUT => Self::Cut,
            SDL_KeyCode_SDLK_COPY => Self::Copy,
            SDL_KeyCode_SDLK_PASTE => Self::Paste,
            SDL_KeyCode_SDLK_FIND => Self::Find,
            SDL_KeyCode_SDLK_MUTE => Self::Mute,
            SDL_KeyCode_SDLK_VOLUMEUP => Self::VolumeUp,
            SDL_KeyCode_SDLK_VOLUMEDOWN => Self::VolumeDown,
            SDL_KeyCode_SDLK_KP_COMMA => Self::KpComma,
            SDL_KeyCode_SDLK_KP_EQUALSAS400 => Self::KpEqualsAS400,
            SDL_KeyCode_SDLK_ALTERASE => Self::AltErase,
            SDL_KeyCode_SDLK_SYSREQ => Self::Sysreq,
            SDL_KeyCode_SDLK_CANCEL => Self::Cancel,
            SDL_KeyCode_SDLK_CLEAR => Self::Clear,
            SDL_KeyCode_SDLK_PRIOR => Self::Prior,
            SDL_KeyCode_SDLK_RETURN2 => Self::Return2,
            SDL_KeyCode_SDLK_SEPARATOR => Self::Separator,
            SDL_KeyCode_SDLK_OUT => Self::Out,
            SDL_KeyCode_SDLK_OPER => Self::Oper,
            SDL_KeyCode_SDLK_CLEARAGAIN => Self::ClearAgain,
            SDL_KeyCode_SDLK_CRSEL => Self::CrSel,
            SDL_KeyCode_SDLK_EXSEL => Self::ExSel,
            SDL_KeyCode_SDLK_KP_00 => Self::Kp00,
            SDL_KeyCode_SDLK_KP_000 => Self::Kp000,
            SDL_KeyCode_SDLK_THOUSANDSSEPARATOR => Self::ThousandsSeparator,
            SDL_KeyCode_SDLK_DECIMALSEPARATOR => Self::DecimalSeparator,
            SDL_KeyCode_SDLK_CURRENCYUNIT => Self::CurrencyUnit,
            SDL_KeyCode_SDLK_CURRENCYSUBUNIT => Self::CurrencySubUnit,
            SDL_KeyCode_SDLK_KP_LEFTPAREN => Self::KpLeftParen,
            SDL_KeyCode_SDLK_KP_RIGHTPAREN => Self::KpRightParen,
            SDL_KeyCode_SDLK_KP_LEFTBRACE => Self::KpLeftBrace,
            SDL_KeyCode_SDLK_KP_RIGHTBRACE => Self::KpRightBrace,
            SDL_KeyCode_SDLK_KP_TAB => Self::KpTab,
            SDL_KeyCode_SDLK_KP_BACKSPACE => Self::KpBackspace,
            _ => Self::Unknown,
        }
    }
}
